namespace CloseEnough {
	public static class WordBank
	{
		public static readonly string[] WORDS = 
		{
			"Dragon",
            "Corned Beef",
            "Ghost",
            "Ship",
            "Baseball",
            "Farm",
            "Pocket",
            "Butterfly",
            "Volcano",
            "Cards",
            "Watch",
            "Mug",
            "Medicine",
            "Roller Coaster",
            "Dream",
            "Puppet",
            "Parent",
            "Onion",
            "Garlic",
            "Blush",
            "Biscuit",
            "Sickness",
            "Pizza",
            "Champion",
            "Stranger",
            "Firefighter",
            "Ice",
            "Window",
            "Thermometer",
            "Beach",
            "Ticket",
            "Dog",
            "String",
            "Shovel",
            "Mailbox",
            "Frankenstein",
            "Zombie",
            "Kite",
            "Psychic",
            "Lover",
            "Romeo and Juliet",
            "Lipstick",
            "Butter",
            "Bear",
            "Volleyball",
            "Fly",
            "Sun",
            "Bite",
            "Work",
            "Fireplace",
            "Angel",
            "Frog",
            "Wagon",
            "Menu",
            "Blind",
            "Ground",
            "Mushroom",
            "Wardrobe",
            "Ice Cream",
            "Faith",
            "Island",
            "Onion",
            "Password",
            "School"         
		};
	}
}