namespace CloseEnough {
	public static class WordBank
	{
		public static readonly string[] WORDS = 
		{
			"Dragon",
            "Corned Beef",
            "Ghost",
            "Ship",
            "Baseball",
            "Farm",
            "Pocket",
            "Butterfly",
            "Volcano",
            "Cards",
            "Watch",
            "Mug",
            "Medicine",
            "Roller Coaster",
            "Dream",
            "Puppet",
            "Parent",
            "Onion",
            "Garlic",
            "Blush",
            "Biscuit",
            "Sickness",
            "Pizza",
            "Stranger",
            "Firefighter",
            "Ice",
            "Window",
            "Thermometer",
            "Beach",
            "Ticket",
            "Dog",
            "String",
            "Shovel",
            "Mailbox",
            "Frankenstein",
            "Zombie",
            "Kite",
            "Lover",
            "Lipstick",
            "Butter",
            "Bear",
            "Volleyball",
            "Fly",
            "Sun",
            "Bite",
            "Work",
            "Fireplace",
            "Angel",
            "Frog",
            "Wagon",
            "Menu",
            "Blind",
            "Ground",
            "Mushroom",
            "Wardrobe",
            "Ice Cream",
            "Faith",
            "Island",
            "Onion",
            "Password",
            "School",
            "Chopsticks",
            "Emergency",
            "Wizard",
            "Car",
            "Rain",
            "Hair",
            "Truck",
            "Airplane",
            "Map",
            "Scale",
            "Shadow",
            "Night",
            "Bedtime",
            "Alarm",
            "Idea",
            "Photograph",
            "Door",
            "Treasure",
            "Pirate",
            "Whistle",
            "Song",
            "Bicycle",
            "Hot Dog",
            "Thief",
            "Spring",
            "Skate",
            "Wax",
            "Cake",
            "Palace",
            "Queen",
            "Salt",
            "Fabric",
            "Exercise",
            "Drought",
            "Baguette",
            "Avocado",
            "Koala",
            "Internet",
            "Celebration",
            "Anaconda",
            "Passenger",
            "Warning",
            "Caution",
            "Stationary",
            "Station",
            "Juice",
            "Thirsty",
            "Geography",
            "Geology",
            "Eye of the Storm",
            "Climate Change",
            "Survival",
            "Cooperate",
            "Rescue",
            "Savior",
            "Danger",
            "Pelican",
            "Predator",
            "Weather",
            "Witch",
            "Sorceress",
            "Warlock",
            "Paladin",
            "Knight",
            "Danger",
            "Farmer",
            "Laboratory",
            "Militia",
            "Shanty Town",
            "Coffee",
            "Pillow",
            "Lighthouse",
            "Political Science",
            "Clock",
            "Mattress",
            "Piano",
            "Peanut Butter and Jelly",
            "Refridgerator",
            "Fast Food",
            "Windmill",
            "Chicken Wings",
            "Geometry",
            "World",
            "Tarot Cards",
            "Mistletoe",
            "Salted Caramel",
            "Spy",
            "Secret Agent",
            "Virtual Reality",
            "Thanksgiving Dinner",
            "Fireworks",
            "Hero",
            "Psychic",
            "Bunk Bed",
            "Fence",
            "Railing",
            "Chainsaw",
            "Treadmill",
            "Salt",
            "Pepper",
            "Ramen",
            "Levels",
            "Teacher",
            "Fairy",
            "Devil",
            "Demon",
            "Friend",
            "Age",
            "Penguin",
            "Anime",
            "Steam",
            "Paintball",
            "Boat",
            "Bamboo",
            "Float",
            "Life Jacket",
            "Omelette",
            "Cheese",
            "Wine",
            "Video Games",
            "Croissant",
            "Stage",
            "Marshmallow"
		};
	}
}